// Generated by gencpp from file stoch3_msgs/ControllerSupervisorStateRequest.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_CONTROLLERSUPERVISORSTATEREQUEST_H
#define STOCH3_MSGS_MESSAGE_CONTROLLERSUPERVISORSTATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stoch3_msgs
{
template <class ContainerAllocator>
struct ControllerSupervisorStateRequest_
{
  typedef ControllerSupervisorStateRequest_<ContainerAllocator> Type;

  ControllerSupervisorStateRequest_()
    {
    }
  ControllerSupervisorStateRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerSupervisorStateRequest_

typedef ::stoch3_msgs::ControllerSupervisorStateRequest_<std::allocator<void> > ControllerSupervisorStateRequest;

typedef boost::shared_ptr< ::stoch3_msgs::ControllerSupervisorStateRequest > ControllerSupervisorStateRequestPtr;
typedef boost::shared_ptr< ::stoch3_msgs::ControllerSupervisorStateRequest const> ControllerSupervisorStateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/ControllerSupervisorStateRequest";
  }

  static const char* value(const ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerSupervisorStateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::stoch3_msgs::ControllerSupervisorStateRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_CONTROLLERSUPERVISORSTATEREQUEST_H
