// Generated by gencpp from file stoch3_msgs/ControllerSupervisorState.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_CONTROLLERSUPERVISORSTATE_H
#define STOCH3_MSGS_MESSAGE_CONTROLLERSUPERVISORSTATE_H

#include <ros/service_traits.h>


#include <stoch3_msgs/ControllerSupervisorStateRequest.h>
#include <stoch3_msgs/ControllerSupervisorStateResponse.h>


namespace stoch3_msgs
{

struct ControllerSupervisorState
{

typedef ControllerSupervisorStateRequest Request;
typedef ControllerSupervisorStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControllerSupervisorState
} // namespace stoch3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stoch3_msgs::ControllerSupervisorState > {
  static const char* value()
  {
    return "61f9a8ff34ea0f4986898104d7e20d25";
  }

  static const char* value(const ::stoch3_msgs::ControllerSupervisorState&) { return value(); }
};

template<>
struct DataType< ::stoch3_msgs::ControllerSupervisorState > {
  static const char* value()
  {
    return "stoch3_msgs/ControllerSupervisorState";
  }

  static const char* value(const ::stoch3_msgs::ControllerSupervisorState&) { return value(); }
};


// service_traits::MD5Sum< ::stoch3_msgs::ControllerSupervisorStateRequest> should match
// service_traits::MD5Sum< ::stoch3_msgs::ControllerSupervisorState >
template<>
struct MD5Sum< ::stoch3_msgs::ControllerSupervisorStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stoch3_msgs::ControllerSupervisorState >::value();
  }
  static const char* value(const ::stoch3_msgs::ControllerSupervisorStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stoch3_msgs::ControllerSupervisorStateRequest> should match
// service_traits::DataType< ::stoch3_msgs::ControllerSupervisorState >
template<>
struct DataType< ::stoch3_msgs::ControllerSupervisorStateRequest>
{
  static const char* value()
  {
    return DataType< ::stoch3_msgs::ControllerSupervisorState >::value();
  }
  static const char* value(const ::stoch3_msgs::ControllerSupervisorStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stoch3_msgs::ControllerSupervisorStateResponse> should match
// service_traits::MD5Sum< ::stoch3_msgs::ControllerSupervisorState >
template<>
struct MD5Sum< ::stoch3_msgs::ControllerSupervisorStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stoch3_msgs::ControllerSupervisorState >::value();
  }
  static const char* value(const ::stoch3_msgs::ControllerSupervisorStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stoch3_msgs::ControllerSupervisorStateResponse> should match
// service_traits::DataType< ::stoch3_msgs::ControllerSupervisorState >
template<>
struct DataType< ::stoch3_msgs::ControllerSupervisorStateResponse>
{
  static const char* value()
  {
    return DataType< ::stoch3_msgs::ControllerSupervisorState >::value();
  }
  static const char* value(const ::stoch3_msgs::ControllerSupervisorStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_CONTROLLERSUPERVISORSTATE_H
