// Generated by gencpp from file stoch3_msgs/Gait.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_GAIT_H
#define STOCH3_MSGS_MESSAGE_GAIT_H

#include <ros/service_traits.h>


#include <stoch3_msgs/GaitRequest.h>
#include <stoch3_msgs/GaitResponse.h>


namespace stoch3_msgs
{

struct Gait
{

typedef GaitRequest Request;
typedef GaitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Gait
} // namespace stoch3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stoch3_msgs::Gait > {
  static const char* value()
  {
    return "e17f1b3fe4a600b5b71bcddef43f4905";
  }

  static const char* value(const ::stoch3_msgs::Gait&) { return value(); }
};

template<>
struct DataType< ::stoch3_msgs::Gait > {
  static const char* value()
  {
    return "stoch3_msgs/Gait";
  }

  static const char* value(const ::stoch3_msgs::Gait&) { return value(); }
};


// service_traits::MD5Sum< ::stoch3_msgs::GaitRequest> should match
// service_traits::MD5Sum< ::stoch3_msgs::Gait >
template<>
struct MD5Sum< ::stoch3_msgs::GaitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stoch3_msgs::Gait >::value();
  }
  static const char* value(const ::stoch3_msgs::GaitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stoch3_msgs::GaitRequest> should match
// service_traits::DataType< ::stoch3_msgs::Gait >
template<>
struct DataType< ::stoch3_msgs::GaitRequest>
{
  static const char* value()
  {
    return DataType< ::stoch3_msgs::Gait >::value();
  }
  static const char* value(const ::stoch3_msgs::GaitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stoch3_msgs::GaitResponse> should match
// service_traits::MD5Sum< ::stoch3_msgs::Gait >
template<>
struct MD5Sum< ::stoch3_msgs::GaitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stoch3_msgs::Gait >::value();
  }
  static const char* value(const ::stoch3_msgs::GaitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stoch3_msgs::GaitResponse> should match
// service_traits::DataType< ::stoch3_msgs::Gait >
template<>
struct DataType< ::stoch3_msgs::GaitResponse>
{
  static const char* value()
  {
    return DataType< ::stoch3_msgs::Gait >::value();
  }
  static const char* value(const ::stoch3_msgs::GaitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_GAIT_H
