// Generated by gencpp from file stoch3_msgs/LegCommand.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_LEGCOMMAND_H
#define STOCH3_MSGS_MESSAGE_LEGCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace stoch3_msgs
{
template <class ContainerAllocator>
struct LegCommand_
{
  typedef LegCommand_<ContainerAllocator> Type;

  LegCommand_()
    : position()
    , velocity()
    , force()
    , kp_scale(0.0)
    , kd_scale(0.0)  {
    }
  LegCommand_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , velocity(_alloc)
    , force(_alloc)
    , kp_scale(0.0)
    , kd_scale(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef double _kp_scale_type;
  _kp_scale_type kp_scale;

   typedef double _kd_scale_type;
  _kd_scale_type kd_scale;





  typedef boost::shared_ptr< ::stoch3_msgs::LegCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::LegCommand_<ContainerAllocator> const> ConstPtr;

}; // struct LegCommand_

typedef ::stoch3_msgs::LegCommand_<std::allocator<void> > LegCommand;

typedef boost::shared_ptr< ::stoch3_msgs::LegCommand > LegCommandPtr;
typedef boost::shared_ptr< ::stoch3_msgs::LegCommand const> LegCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::LegCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::LegCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stoch3_msgs::LegCommand_<ContainerAllocator1> & lhs, const ::stoch3_msgs::LegCommand_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.force == rhs.force &&
    lhs.kp_scale == rhs.kp_scale &&
    lhs.kd_scale == rhs.kd_scale;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stoch3_msgs::LegCommand_<ContainerAllocator1> & lhs, const ::stoch3_msgs::LegCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::LegCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::LegCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::LegCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::LegCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::LegCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::LegCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::LegCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecee7b804ccb7dfdc74daea16cd92c3f";
  }

  static const char* value(const ::stoch3_msgs::LegCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xecee7b804ccb7dfdULL;
  static const uint64_t static_value2 = 0xc74daea16cd92c3fULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::LegCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/LegCommand";
  }

  static const char* value(const ::stoch3_msgs::LegCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::LegCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Vector3 position   # Position of foot\n"
"geometry_msgs/Vector3 velocity   # Velocity of foot\n"
"geometry_msgs/Vector3 force      # Force exerted by foot on environment\n"
"float64 kp_scale\n"
"float64 kd_scale\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::stoch3_msgs::LegCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::LegCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.force);
      stream.next(m.kp_scale);
      stream.next(m.kd_scale);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::LegCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stoch3_msgs::LegCommand_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "kp_scale: ";
    Printer<double>::stream(s, indent + "  ", v.kp_scale);
    s << indent << "kd_scale: ";
    Printer<double>::stream(s, indent + "  ", v.kd_scale);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_LEGCOMMAND_H
