// Generated by gencpp from file stoch3_msgs/LegCommandStamped.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_LEGCOMMANDSTAMPED_H
#define STOCH3_MSGS_MESSAGE_LEGCOMMANDSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <stoch3_msgs/LegCommand.h>

namespace stoch3_msgs
{
template <class ContainerAllocator>
struct LegCommandStamped_
{
  typedef LegCommandStamped_<ContainerAllocator> Type;

  LegCommandStamped_()
    : header()
    , data()  {
    }
  LegCommandStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::stoch3_msgs::LegCommand_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> const> ConstPtr;

}; // struct LegCommandStamped_

typedef ::stoch3_msgs::LegCommandStamped_<std::allocator<void> > LegCommandStamped;

typedef boost::shared_ptr< ::stoch3_msgs::LegCommandStamped > LegCommandStampedPtr;
typedef boost::shared_ptr< ::stoch3_msgs::LegCommandStamped const> LegCommandStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator1> & lhs, const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator1> & lhs, const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5604be9aee7bde9f6baa5a2ee1398f28";
  }

  static const char* value(const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5604be9aee7bde9fULL;
  static const uint64_t static_value2 = 0x6baa5a2ee1398f28ULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/LegCommandStamped";
  }

  static const char* value(const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"stoch3_msgs/LegCommand data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: stoch3_msgs/LegCommand\n"
"geometry_msgs/Vector3 position   # Position of foot\n"
"geometry_msgs/Vector3 velocity   # Velocity of foot\n"
"geometry_msgs/Vector3 force      # Force exerted by foot on environment\n"
"float64 kp_scale\n"
"float64 kd_scale\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegCommandStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::LegCommandStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stoch3_msgs::LegCommandStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::stoch3_msgs::LegCommand_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_LEGCOMMANDSTAMPED_H
