// Generated by gencpp from file stoch3_msgs/LegState.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_LEGSTATE_H
#define STOCH3_MSGS_MESSAGE_LEGSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace stoch3_msgs
{
template <class ContainerAllocator>
struct LegState_
{
  typedef LegState_<ContainerAllocator> Type;

  LegState_()
    : name()
    , position()
    , velocity()
    , force()
    , support_probability(0.0)  {
    }
  LegState_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , force(_alloc)
    , support_probability(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _force_type;
  _force_type force;

   typedef double _support_probability_type;
  _support_probability_type support_probability;





  typedef boost::shared_ptr< ::stoch3_msgs::LegState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::LegState_<ContainerAllocator> const> ConstPtr;

}; // struct LegState_

typedef ::stoch3_msgs::LegState_<std::allocator<void> > LegState;

typedef boost::shared_ptr< ::stoch3_msgs::LegState > LegStatePtr;
typedef boost::shared_ptr< ::stoch3_msgs::LegState const> LegStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::LegState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::LegState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stoch3_msgs::LegState_<ContainerAllocator1> & lhs, const ::stoch3_msgs::LegState_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.force == rhs.force &&
    lhs.support_probability == rhs.support_probability;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stoch3_msgs::LegState_<ContainerAllocator1> & lhs, const ::stoch3_msgs::LegState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::LegState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::LegState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::LegState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::LegState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::LegState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::LegState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::LegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "796e284058360fe14a241d0db59e274d";
  }

  static const char* value(const ::stoch3_msgs::LegState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x796e284058360fe1ULL;
  static const uint64_t static_value2 = 0x4a241d0db59e274dULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::LegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/LegState";
  }

  static const char* value(const ::stoch3_msgs::LegState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::LegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 force\n"
"float64 support_probability        # [0, 1] , probability that the leg is a support leg.\n"
"                                   # Limit the value to range [0, 1] if it is outside the range.\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::stoch3_msgs::LegState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::LegState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.force);
      stream.next(m.support_probability);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::LegState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stoch3_msgs::LegState_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "force: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.force);
    s << indent << "support_probability: ";
    Printer<double>::stream(s, indent + "  ", v.support_probability);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_LEGSTATE_H
