// Generated by gencpp from file stoch3_msgs/LegStateStamped.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_LEGSTATESTAMPED_H
#define STOCH3_MSGS_MESSAGE_LEGSTATESTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <stoch3_msgs/LegState.h>

namespace stoch3_msgs
{
template <class ContainerAllocator>
struct LegStateStamped_
{
  typedef LegStateStamped_<ContainerAllocator> Type;

  LegStateStamped_()
    : header()
    , data()  {
    }
  LegStateStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::stoch3_msgs::LegState_<ContainerAllocator>  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> const> ConstPtr;

}; // struct LegStateStamped_

typedef ::stoch3_msgs::LegStateStamped_<std::allocator<void> > LegStateStamped;

typedef boost::shared_ptr< ::stoch3_msgs::LegStateStamped > LegStateStampedPtr;
typedef boost::shared_ptr< ::stoch3_msgs::LegStateStamped const> LegStateStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::LegStateStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stoch3_msgs::LegStateStamped_<ContainerAllocator1> & lhs, const ::stoch3_msgs::LegStateStamped_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stoch3_msgs::LegStateStamped_<ContainerAllocator1> & lhs, const ::stoch3_msgs::LegStateStamped_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b8a8ec9ab64dc6e73badf36e24479af3";
  }

  static const char* value(const ::stoch3_msgs::LegStateStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb8a8ec9ab64dc6e7ULL;
  static const uint64_t static_value2 = 0x3badf36e24479af3ULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/LegStateStamped";
  }

  static const char* value(const ::stoch3_msgs::LegStateStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"stoch3_msgs/LegState data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: stoch3_msgs/LegState\n"
"string name\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 force\n"
"float64 support_probability        # [0, 1] , probability that the leg is a support leg.\n"
"                                   # Limit the value to range [0, 1] if it is outside the range.\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::stoch3_msgs::LegStateStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LegStateStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::LegStateStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stoch3_msgs::LegStateStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    s << std::endl;
    Printer< ::stoch3_msgs::LegState_<ContainerAllocator> >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_LEGSTATESTAMPED_H
