// Generated by gencpp from file stoch3_msgs/QuadrupedLegState.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_QUADRUPEDLEGSTATE_H
#define STOCH3_MSGS_MESSAGE_QUADRUPEDLEGSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <stoch3_msgs/LegState.h>
#include <stoch3_msgs/LegState.h>
#include <stoch3_msgs/LegState.h>
#include <stoch3_msgs/LegState.h>

namespace stoch3_msgs
{
template <class ContainerAllocator>
struct QuadrupedLegState_
{
  typedef QuadrupedLegState_<ContainerAllocator> Type;

  QuadrupedLegState_()
    : header()
    , fl()
    , fr()
    , bl()
    , br()  {
    }
  QuadrupedLegState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , fl(_alloc)
    , fr(_alloc)
    , bl(_alloc)
    , br(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::stoch3_msgs::LegState_<ContainerAllocator>  _fl_type;
  _fl_type fl;

   typedef  ::stoch3_msgs::LegState_<ContainerAllocator>  _fr_type;
  _fr_type fr;

   typedef  ::stoch3_msgs::LegState_<ContainerAllocator>  _bl_type;
  _bl_type bl;

   typedef  ::stoch3_msgs::LegState_<ContainerAllocator>  _br_type;
  _br_type br;





  typedef boost::shared_ptr< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> const> ConstPtr;

}; // struct QuadrupedLegState_

typedef ::stoch3_msgs::QuadrupedLegState_<std::allocator<void> > QuadrupedLegState;

typedef boost::shared_ptr< ::stoch3_msgs::QuadrupedLegState > QuadrupedLegStatePtr;
typedef boost::shared_ptr< ::stoch3_msgs::QuadrupedLegState const> QuadrupedLegStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator1> & lhs, const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.fl == rhs.fl &&
    lhs.fr == rhs.fr &&
    lhs.bl == rhs.bl &&
    lhs.br == rhs.br;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator1> & lhs, const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bf5e523a21942d2ff068a9be010f7df1";
  }

  static const char* value(const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbf5e523a21942d2fULL;
  static const uint64_t static_value2 = 0xf068a9be010f7df1ULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/QuadrupedLegState";
  }

  static const char* value(const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"stoch3_msgs/LegState fl\n"
"stoch3_msgs/LegState fr\n"
"stoch3_msgs/LegState bl\n"
"stoch3_msgs/LegState br\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: stoch3_msgs/LegState\n"
"string name\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 force\n"
"float64 support_probability        # [0, 1] , probability that the leg is a support leg.\n"
"                                   # Limit the value to range [0, 1] if it is outside the range.\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.fl);
      stream.next(m.fr);
      stream.next(m.bl);
      stream.next(m.br);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadrupedLegState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stoch3_msgs::QuadrupedLegState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "fl: ";
    s << std::endl;
    Printer< ::stoch3_msgs::LegState_<ContainerAllocator> >::stream(s, indent + "  ", v.fl);
    s << indent << "fr: ";
    s << std::endl;
    Printer< ::stoch3_msgs::LegState_<ContainerAllocator> >::stream(s, indent + "  ", v.fr);
    s << indent << "bl: ";
    s << std::endl;
    Printer< ::stoch3_msgs::LegState_<ContainerAllocator> >::stream(s, indent + "  ", v.bl);
    s << indent << "br: ";
    s << std::endl;
    Printer< ::stoch3_msgs::LegState_<ContainerAllocator> >::stream(s, indent + "  ", v.br);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_QUADRUPEDLEGSTATE_H
