// Generated by gencpp from file stoch3_msgs/SitStandGoal.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_SITSTANDGOAL_H
#define STOCH3_MSGS_MESSAGE_SITSTANDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stoch3_msgs
{
template <class ContainerAllocator>
struct SitStandGoal_
{
  typedef SitStandGoal_<ContainerAllocator> Type;

  SitStandGoal_()
    : posture()  {
    }
  SitStandGoal_(const ContainerAllocator& _alloc)
    : posture(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _posture_type;
  _posture_type posture;





  typedef boost::shared_ptr< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SitStandGoal_

typedef ::stoch3_msgs::SitStandGoal_<std::allocator<void> > SitStandGoal;

typedef boost::shared_ptr< ::stoch3_msgs::SitStandGoal > SitStandGoalPtr;
typedef boost::shared_ptr< ::stoch3_msgs::SitStandGoal const> SitStandGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::SitStandGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stoch3_msgs::SitStandGoal_<ContainerAllocator1> & lhs, const ::stoch3_msgs::SitStandGoal_<ContainerAllocator2> & rhs)
{
  return lhs.posture == rhs.posture;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stoch3_msgs::SitStandGoal_<ContainerAllocator1> & lhs, const ::stoch3_msgs::SitStandGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7592b1dc423dc165bc03d21a94026564";
  }

  static const char* value(const ::stoch3_msgs::SitStandGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7592b1dc423dc165ULL;
  static const uint64_t static_value2 = 0xbc03d21a94026564ULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/SitStandGoal";
  }

  static const char* value(const ::stoch3_msgs::SitStandGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"string posture\n"
;
  }

  static const char* value(const ::stoch3_msgs::SitStandGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posture);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SitStandGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::SitStandGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stoch3_msgs::SitStandGoal_<ContainerAllocator>& v)
  {
    s << indent << "posture: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.posture);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_SITSTANDGOAL_H
