// Generated by gencpp from file stoch3_msgs/SitStandResult.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_SITSTANDRESULT_H
#define STOCH3_MSGS_MESSAGE_SITSTANDRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stoch3_msgs
{
template <class ContainerAllocator>
struct SitStandResult_
{
  typedef SitStandResult_<ContainerAllocator> Type;

  SitStandResult_()
    : progress(0.0)  {
    }
  SitStandResult_(const ContainerAllocator& _alloc)
    : progress(0.0)  {
  (void)_alloc;
    }



   typedef float _progress_type;
  _progress_type progress;





  typedef boost::shared_ptr< ::stoch3_msgs::SitStandResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::SitStandResult_<ContainerAllocator> const> ConstPtr;

}; // struct SitStandResult_

typedef ::stoch3_msgs::SitStandResult_<std::allocator<void> > SitStandResult;

typedef boost::shared_ptr< ::stoch3_msgs::SitStandResult > SitStandResultPtr;
typedef boost::shared_ptr< ::stoch3_msgs::SitStandResult const> SitStandResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::SitStandResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stoch3_msgs::SitStandResult_<ContainerAllocator1> & lhs, const ::stoch3_msgs::SitStandResult_<ContainerAllocator2> & rhs)
{
  return lhs.progress == rhs.progress;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stoch3_msgs::SitStandResult_<ContainerAllocator1> & lhs, const ::stoch3_msgs::SitStandResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::SitStandResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::SitStandResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::SitStandResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70805092fd20e110765c7b79e8efb737";
  }

  static const char* value(const ::stoch3_msgs::SitStandResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70805092fd20e110ULL;
  static const uint64_t static_value2 = 0x765c7b79e8efb737ULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/SitStandResult";
  }

  static const char* value(const ::stoch3_msgs::SitStandResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"float32 progress\n"
;
  }

  static const char* value(const ::stoch3_msgs::SitStandResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.progress);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SitStandResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::SitStandResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stoch3_msgs::SitStandResult_<ContainerAllocator>& v)
  {
    s << indent << "progress: ";
    Printer<float>::stream(s, indent + "  ", v.progress);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_SITSTANDRESULT_H
