// Generated by gencpp from file stoch3_msgs/SwitchControllerResponse.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_SWITCHCONTROLLERRESPONSE_H
#define STOCH3_MSGS_MESSAGE_SWITCHCONTROLLERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stoch3_msgs
{
template <class ContainerAllocator>
struct SwitchControllerResponse_
{
  typedef SwitchControllerResponse_<ContainerAllocator> Type;

  SwitchControllerResponse_()
    : ok(false)  {
    }
  SwitchControllerResponse_(const ContainerAllocator& _alloc)
    : ok(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;





  typedef boost::shared_ptr< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SwitchControllerResponse_

typedef ::stoch3_msgs::SwitchControllerResponse_<std::allocator<void> > SwitchControllerResponse;

typedef boost::shared_ptr< ::stoch3_msgs::SwitchControllerResponse > SwitchControllerResponsePtr;
typedef boost::shared_ptr< ::stoch3_msgs::SwitchControllerResponse const> SwitchControllerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator1> & lhs, const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator1> & lhs, const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stoch3_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6da3883749771fac40d6deb24a8c02";
  }

  static const char* value(const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6da3883749771fULL;
  static const uint64_t static_value2 = 0xac40d6deb24a8c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stoch3_msgs/SwitchControllerResponse";
  }

  static const char* value(const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ok\n"
"\n"
;
  }

  static const char* value(const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwitchControllerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stoch3_msgs::SwitchControllerResponse_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_SWITCHCONTROLLERRESPONSE_H
