// Generated by gencpp from file stoch3_msgs/SwitchController.msg
// DO NOT EDIT!


#ifndef STOCH3_MSGS_MESSAGE_SWITCHCONTROLLER_H
#define STOCH3_MSGS_MESSAGE_SWITCHCONTROLLER_H

#include <ros/service_traits.h>


#include <stoch3_msgs/SwitchControllerRequest.h>
#include <stoch3_msgs/SwitchControllerResponse.h>


namespace stoch3_msgs
{

struct SwitchController
{

typedef SwitchControllerRequest Request;
typedef SwitchControllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SwitchController
} // namespace stoch3_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::stoch3_msgs::SwitchController > {
  static const char* value()
  {
    return "647e5c54b8d6468952d8d31f1efe96c0";
  }

  static const char* value(const ::stoch3_msgs::SwitchController&) { return value(); }
};

template<>
struct DataType< ::stoch3_msgs::SwitchController > {
  static const char* value()
  {
    return "stoch3_msgs/SwitchController";
  }

  static const char* value(const ::stoch3_msgs::SwitchController&) { return value(); }
};


// service_traits::MD5Sum< ::stoch3_msgs::SwitchControllerRequest> should match
// service_traits::MD5Sum< ::stoch3_msgs::SwitchController >
template<>
struct MD5Sum< ::stoch3_msgs::SwitchControllerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::stoch3_msgs::SwitchController >::value();
  }
  static const char* value(const ::stoch3_msgs::SwitchControllerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::stoch3_msgs::SwitchControllerRequest> should match
// service_traits::DataType< ::stoch3_msgs::SwitchController >
template<>
struct DataType< ::stoch3_msgs::SwitchControllerRequest>
{
  static const char* value()
  {
    return DataType< ::stoch3_msgs::SwitchController >::value();
  }
  static const char* value(const ::stoch3_msgs::SwitchControllerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::stoch3_msgs::SwitchControllerResponse> should match
// service_traits::MD5Sum< ::stoch3_msgs::SwitchController >
template<>
struct MD5Sum< ::stoch3_msgs::SwitchControllerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::stoch3_msgs::SwitchController >::value();
  }
  static const char* value(const ::stoch3_msgs::SwitchControllerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::stoch3_msgs::SwitchControllerResponse> should match
// service_traits::DataType< ::stoch3_msgs::SwitchController >
template<>
struct DataType< ::stoch3_msgs::SwitchControllerResponse>
{
  static const char* value()
  {
    return DataType< ::stoch3_msgs::SwitchController >::value();
  }
  static const char* value(const ::stoch3_msgs::SwitchControllerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STOCH3_MSGS_MESSAGE_SWITCHCONTROLLER_H
