(cl:defpackage stoch3_msgs-srv
  (:use )
  (:export
   "COMMAND"
   "<COMMAND-REQUEST>"
   "COMMAND-REQUEST"
   "<COMMAND-RESPONSE>"
   "COMMAND-RESPONSE"
   "CONTROLLERSUPERVISORSTATE"
   "<CONTROLLERSUPERVISORSTATE-REQUEST>"
   "CONTROLLERSUPERVISORSTATE-REQUEST"
   "<CONTROLLERSUPERVISORSTATE-RESPONSE>"
   "CONTROLLERSUPERVISORSTATE-RESPONSE"
   "GAIT"
   "<GAIT-REQUEST>"
   "GAIT-REQUEST"
   "<GAIT-RESPONSE>"
   "GAIT-RESPONSE"
   "SWITCHCONTROLLER"
   "<SWITCHCONTROLLER-REQUEST>"
   "SWITCHCONTROLLER-REQUEST"
   "<SWITCHCONTROLLER-RESPONSE>"
   "SWITCHCONTROLLER-RESPONSE"
  ))

