; Auto-generated. Do not edit!


(cl:in-package stoch3_msgs-msg)


;//! \htmlinclude SitStandGoal.msg.html

(cl:defclass <SitStandGoal> (roslisp-msg-protocol:ros-message)
  ((posture
    :reader posture
    :initarg :posture
    :type cl:string
    :initform ""))
)

(cl:defclass SitStandGoal (<SitStandGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SitStandGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SitStandGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stoch3_msgs-msg:<SitStandGoal> is deprecated: use stoch3_msgs-msg:SitStandGoal instead.")))

(cl:ensure-generic-function 'posture-val :lambda-list '(m))
(cl:defmethod posture-val ((m <SitStandGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stoch3_msgs-msg:posture-val is deprecated.  Use stoch3_msgs-msg:posture instead.")
  (posture m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SitStandGoal>) ostream)
  "Serializes a message object of type '<SitStandGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'posture))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'posture))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SitStandGoal>) istream)
  "Deserializes a message object of type '<SitStandGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'posture) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'posture) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SitStandGoal>)))
  "Returns string type for a message object of type '<SitStandGoal>"
  "stoch3_msgs/SitStandGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SitStandGoal)))
  "Returns string type for a message object of type 'SitStandGoal"
  "stoch3_msgs/SitStandGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SitStandGoal>)))
  "Returns md5sum for a message object of type '<SitStandGoal>"
  "7592b1dc423dc165bc03d21a94026564")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SitStandGoal)))
  "Returns md5sum for a message object of type 'SitStandGoal"
  "7592b1dc423dc165bc03d21a94026564")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SitStandGoal>)))
  "Returns full string definition for message of type '<SitStandGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string posture~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SitStandGoal)))
  "Returns full string definition for message of type 'SitStandGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%string posture~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SitStandGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'posture))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SitStandGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SitStandGoal
    (cl:cons ':posture (posture msg))
))
