---
string controller_name # Name of the current active controller
int64  seq_num         # Sequence numer of the current active controller
                       # (i.e, number of times the controller update function called since it became active)
