// Auto-generated. Do not edit!

// (in-package stoch3_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class SitStandGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.posture = null;
    }
    else {
      if (initObj.hasOwnProperty('posture')) {
        this.posture = initObj.posture
      }
      else {
        this.posture = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type SitStandGoal
    // Serialize message field [posture]
    bufferOffset = _serializer.string(obj.posture, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type SitStandGoal
    let len;
    let data = new SitStandGoal(null);
    // Deserialize message field [posture]
    data.posture = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.posture.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'stoch3_msgs/SitStandGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '7592b1dc423dc165bc03d21a94026564';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    string posture
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new SitStandGoal(null);
    if (msg.posture !== undefined) {
      resolved.posture = msg.posture;
    }
    else {
      resolved.posture = ''
    }

    return resolved;
    }
};

module.exports = SitStandGoal;
