joint_limits:
  fl_abd_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 7.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 100.0
  fl_hip_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 7.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 100.0  
  fl_knee_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 10.0
    has_acceleration_limits: false
    max_acceleration: 7.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 100.0  
  fr_abd_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
  fr_hip_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
  fr_knee_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
  bl_abd_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
  bl_hip_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
  bl_knee_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
  br_abd_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
  br_hip_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
  br_knee_joint:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 3.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: false
    max_jerk: 100.0
    has_effort_limits: false
    max_effort: 1.0  
